/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PiecesNewRouteImport } from './routes/pieces.new'
import { Route as PiecesIdIndexRouteImport } from './routes/pieces.$id.index'
import { Route as PiecesIdEditRouteImport } from './routes/pieces.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PiecesNewRoute = PiecesNewRouteImport.update({
  id: '/pieces/new',
  path: '/pieces/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PiecesIdIndexRoute = PiecesIdIndexRouteImport.update({
  id: '/pieces/$id/',
  path: '/pieces/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PiecesIdEditRoute = PiecesIdEditRouteImport.update({
  id: '/pieces/$id/edit',
  path: '/pieces/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/pieces/new': typeof PiecesNewRoute
  '/pieces/$id/edit': typeof PiecesIdEditRoute
  '/pieces/$id/': typeof PiecesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/pieces/new': typeof PiecesNewRoute
  '/pieces/$id/edit': typeof PiecesIdEditRoute
  '/pieces/$id': typeof PiecesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/pieces/new': typeof PiecesNewRoute
  '/pieces/$id/edit': typeof PiecesIdEditRoute
  '/pieces/$id/': typeof PiecesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/pieces/new'
    | '/pieces/$id/edit'
    | '/pieces/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/pieces/new'
    | '/pieces/$id/edit'
    | '/pieces/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/pieces/new'
    | '/pieces/$id/edit'
    | '/pieces/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  PiecesNewRoute: typeof PiecesNewRoute
  PiecesIdEditRoute: typeof PiecesIdEditRoute
  PiecesIdIndexRoute: typeof PiecesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pieces/new': {
      id: '/pieces/new'
      path: '/pieces/new'
      fullPath: '/pieces/new'
      preLoaderRoute: typeof PiecesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pieces/$id/': {
      id: '/pieces/$id/'
      path: '/pieces/$id'
      fullPath: '/pieces/$id/'
      preLoaderRoute: typeof PiecesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pieces/$id/edit': {
      id: '/pieces/$id/edit'
      path: '/pieces/$id/edit'
      fullPath: '/pieces/$id/edit'
      preLoaderRoute: typeof PiecesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  PiecesNewRoute: PiecesNewRoute,
  PiecesIdEditRoute: PiecesIdEditRoute,
  PiecesIdIndexRoute: PiecesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
